import type { Metadata } from "next";
import { Kiwi_Maru, Tenor_Sans } from "next/font/google";
import "./globals.css";
import { Header } from "@/Components/Header/Header";

const kiwiMaru = Kiwi_Maru({
  variable: "--font-kiwi-maru",
  subsets: ["latin"],
  weight: ["300", "400", "500"],
});

const tenorSans = Tenor_Sans({
  variable: "--font-tenor-sans",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Vets for Pets",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body
        className={`flex flex-col min-h-screen ${kiwiMaru.variable} ${tenorSans.variable} antialiased`}
      >
        <Header />
        <div className="flex flex-col flex-grow">{children}</div>
        {/* <Footer /> */}
      </body>
    </html>
  );
}
